use_frameworks!
platform :ios, '9.0'


target 'iOSKit_Example' do

  pod 'JacKit',     :path => '../../JacKit/'
  pod 'iOSKit',     :path => '../'
  pod 'iOSKit/MBP', :path => '../'
  pod 'iOSKit/SVP', :path => '../'

  pod 'Eureka'

  target 'iOSKit_ExampleTests' do
    inherit! :search_paths


  end
end
