use_frameworks!
platform :ios, '9.0'


target 'iOSKit_Example' do
  pod 'JacKit', :path => '../../JacKit/'
  pod 'iOSKit', :path => '../'

  target 'iOSKit_Tests' do
    inherit! :search_paths


  end
end
